"""empty message

Revision ID: c95a2606e617
Revises: bcd3b8df57be
Create Date: 2025-09-01 23:24:02.978410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95a2606e617'
down_revision = 'bcd3b8df57be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_code_expired', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mobile_code_expired')

    # ### end Alembic commands ###
